# SEO settings
title             : "Fiction Coach"
hpg_description   : "Write better stories"
description       : "Write better stories. With solid case studies from great books, cult movies, beloved series and kick-ass games!"
url               : "https://fiction.coach"
baseurl           : "" # apply repo name if use it under gh-pages branch
repo              : https://github.com/fictioncoach/fictioncoach.github.io/
comments          : false
paginate_path   : "/page:num/"

_ga : "UA-120149424-1"

author: "Richard Crimson"
image: "/assets/images/red.png"

# Build settings
permalink     : /:year/:month/:title
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Social
github_username   : "fictioncoach"
twitter_username  : "theplotdude"
twitter_site      : "theplotdude"
twitter_card      : "summary_large_image"

defaults:
  -
    scope:
      path: 'bower_components'
    values:
      sitemap: false

plugins:
  - bourbon
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-json-feed
  - jekyll/tagging

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

categories: ["movies", "games", "books", "series", "writing"]

tag_page_data:
  sitemap: false
tag_permalink_style: pretty
tag_page_layout: tags
tag_page_dir: tag
tag_cloud: ["Book Studies", "Character", "Concept", "Darth Vader", "Editor advice", "Fantastic Beasts", "Foreshadowing", "Games", "Game Of Thrones", "got", "Harry Potter", "JK Rowling", "Movies", "Series", "Star Wars", "SW", "Structure", "Theme", "Villains", "Voice"]

sitemap_list_title: Fiction Coach Sitemap
sitemap:
- title: Home
  url: /
- title: About & Contact
  url: contact
- title: How We Use Cookies
  url: cookies
- title: Privacy Policy
  url: privacy
- title: Sitemap
  url: sitemap
- title: Case Studies
  url: case-studies
  subfolderitems:
    - page: Book Studies
      url: /tag/book-studies
    - page: Series
      url: /tag/series
    - page: Movies
      url: /tag/movies
    - page: Games
      url: /tag/games
- title: On Writing
  url: on-writing
  subfolderitems:
    - page: Theme
      url: /tag/theme
    - page: Concept
      url: /tag/concept
    - page: Character
      url: /tag/character
    - page: Structure
      url: /tag/structure
    - page: Voice
      url: /tag/voice
    - page: Editor's orders
      url: /tag/on-writing

left_header_navigation:
  - title: On Writing
    url: on-writing
    subfolderitems:
      - page: Foreshadowing
        url: /tag/foreshadowing
      - page: Write like Rowling
        url: /2018/06/how-to-write-like-jk-rowling
      - page: Theme
        url: /tag/theme
      - page: Concept
        url: /tag/concept
      - page: Character
        url: /tag/character
      - page: Structure
        url: /tag/structure
      - page: Voice
        url: /tag/voice
      - page: Editor's orders
        url: /tag/on-writing

header_navigation:
- title: Case Studies
  url: case-studies
  subfolderitems:
    - page: Book Studies
      categ: "books"
      url: /tag/book-studies
    - page: Series
      categ: "series"
      url: /tag/series
    - page: Movies
      categ: "movies"
      url: /tag/movies
    - page: Games
      categ: "games"
      url: /tag/games

category_tree:
- page: Book Studies
  categ: "books"
  url: /tag/book-studies
- page: Series
  categ: "series"
  url: /tag/series
- page: Movies
  categ: "movies"
  url: /tag/movies
- page: Games
  categ: "games"
  url: /tag/games
- page: On Writing
  categ: "writing"
  url: /on-writing

footer_nav_col_1:
  - title: Contact
    url: /contact
  - title: About
    url: /about
  - title: How we use cookies
    url: /cookies
  - title: Privacy Policy
    url: /privacy
  - title: Sitemap
    url: /sitemap
footer_nav_col_2:
  - title: Book Studies
    url: /tag/book-studies
  - title: Series
    url: /tag/series
  - title: Movies
    url: /tag/movies
  - title: Games
    url: /tag/games
